quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/todo_db
quarkus.datasource.username=postgres
quarkus.datasource.password=Senha@123
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true